version: '3.8'

services:
  snake-game:
    build: ./src
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://snakegame:password@db:5432/snakegame
      - FLASK_ENV=development
      - DEBUG=true
    depends_on:
      - db
    volumes:
      - ./src:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=snakegame
      - POSTGRES_USER=snakegame
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: